-- Seed data: sample institution, programmes, PLOs and subjects.
-- Subject codes/CLOs are illustrative samples for the demo; edit them in Admin → Curriculum.
INSERT INTO institutions (id,name,short_name,city) VALUES (1,'Universiti Teknikal Malaysia Melaka','UTeM','Melaka');
INSERT INTO faculties (id,institution_id,name,short_name) VALUES (1,1,'Fakulti Teknologi Maklumat dan Komunikasi','FTMK');
INSERT INTO programmes (id,faculty_id,name,level) VALUES (1,1,'Bachelor of Cloud Computing and Applications with Honours','Bachelor');
INSERT INTO programmes (id,faculty_id,name,level) VALUES (2,1,'Bachelor of Computer Science (Software Development) with Honours','Bachelor');
INSERT INTO programmes (id,faculty_id,name,level) VALUES (3,1,'Bachelor of Computer Science (Artificial Intelligence) with Honours','Bachelor');
INSERT INTO programmes (id,faculty_id,name,level) VALUES (4,1,'Bachelor of Computer Science (Computer Networking) with Honours','Bachelor');
INSERT INTO programmes (id,faculty_id,name,level) VALUES (5,1,'Bachelor of Computer Science (Computer Security) with Honours','Bachelor');
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (1,'PLO1','Knowledge','Apply knowledge of computing fundamentals and the specialisation to solve computing problems.',0);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (1,'PLO2','Cognitive','Analyse complex problems and design computing solutions using appropriate methods.',1);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (1,'PLO3','Practical','Use modern tools, platforms and techniques to build, test and deploy computing systems.',2);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (1,'PLO4','Interpersonal','Work effectively as a member or leader of diverse teams.',3);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (1,'PLO5','Communication','Communicate technical ideas clearly in writing and presentations.',4);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (1,'PLO6','Digital','Use digital technologies and data to support work and decision making.',5);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (1,'PLO7','Numeracy','Apply mathematical and statistical reasoning to computing problems.',6);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (1,'PLO8','Leadership','Demonstrate leadership, autonomy and responsibility in projects.',7);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (1,'PLO9','Personal','Engage in lifelong learning and professional development.',8);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (1,'PLO10','Entrepreneurial','Identify opportunities and apply entrepreneurial thinking to technology solutions.',9);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (1,'PLO11','Ethics','Practise professional, ethical, legal and security-aware conduct in computing.',10);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (2,'PLO1','Knowledge','Apply knowledge of computing fundamentals and the specialisation to solve computing problems.',0);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (2,'PLO2','Cognitive','Analyse complex problems and design computing solutions using appropriate methods.',1);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (2,'PLO3','Practical','Use modern tools, platforms and techniques to build, test and deploy computing systems.',2);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (2,'PLO4','Interpersonal','Work effectively as a member or leader of diverse teams.',3);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (2,'PLO5','Communication','Communicate technical ideas clearly in writing and presentations.',4);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (2,'PLO6','Digital','Use digital technologies and data to support work and decision making.',5);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (2,'PLO7','Numeracy','Apply mathematical and statistical reasoning to computing problems.',6);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (2,'PLO8','Leadership','Demonstrate leadership, autonomy and responsibility in projects.',7);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (2,'PLO9','Personal','Engage in lifelong learning and professional development.',8);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (2,'PLO10','Entrepreneurial','Identify opportunities and apply entrepreneurial thinking to technology solutions.',9);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (2,'PLO11','Ethics','Practise professional, ethical, legal and security-aware conduct in computing.',10);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (3,'PLO1','Knowledge','Apply knowledge of computing fundamentals and the specialisation to solve computing problems.',0);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (3,'PLO2','Cognitive','Analyse complex problems and design computing solutions using appropriate methods.',1);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (3,'PLO3','Practical','Use modern tools, platforms and techniques to build, test and deploy computing systems.',2);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (3,'PLO4','Interpersonal','Work effectively as a member or leader of diverse teams.',3);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (3,'PLO5','Communication','Communicate technical ideas clearly in writing and presentations.',4);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (3,'PLO6','Digital','Use digital technologies and data to support work and decision making.',5);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (3,'PLO7','Numeracy','Apply mathematical and statistical reasoning to computing problems.',6);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (3,'PLO8','Leadership','Demonstrate leadership, autonomy and responsibility in projects.',7);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (3,'PLO9','Personal','Engage in lifelong learning and professional development.',8);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (3,'PLO10','Entrepreneurial','Identify opportunities and apply entrepreneurial thinking to technology solutions.',9);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (3,'PLO11','Ethics','Practise professional, ethical, legal and security-aware conduct in computing.',10);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (4,'PLO1','Knowledge','Apply knowledge of computing fundamentals and the specialisation to solve computing problems.',0);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (4,'PLO2','Cognitive','Analyse complex problems and design computing solutions using appropriate methods.',1);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (4,'PLO3','Practical','Use modern tools, platforms and techniques to build, test and deploy computing systems.',2);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (4,'PLO4','Interpersonal','Work effectively as a member or leader of diverse teams.',3);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (4,'PLO5','Communication','Communicate technical ideas clearly in writing and presentations.',4);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (4,'PLO6','Digital','Use digital technologies and data to support work and decision making.',5);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (4,'PLO7','Numeracy','Apply mathematical and statistical reasoning to computing problems.',6);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (4,'PLO8','Leadership','Demonstrate leadership, autonomy and responsibility in projects.',7);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (4,'PLO9','Personal','Engage in lifelong learning and professional development.',8);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (4,'PLO10','Entrepreneurial','Identify opportunities and apply entrepreneurial thinking to technology solutions.',9);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (4,'PLO11','Ethics','Practise professional, ethical, legal and security-aware conduct in computing.',10);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (5,'PLO1','Knowledge','Apply knowledge of computing fundamentals and the specialisation to solve computing problems.',0);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (5,'PLO2','Cognitive','Analyse complex problems and design computing solutions using appropriate methods.',1);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (5,'PLO3','Practical','Use modern tools, platforms and techniques to build, test and deploy computing systems.',2);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (5,'PLO4','Interpersonal','Work effectively as a member or leader of diverse teams.',3);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (5,'PLO5','Communication','Communicate technical ideas clearly in writing and presentations.',4);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (5,'PLO6','Digital','Use digital technologies and data to support work and decision making.',5);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (5,'PLO7','Numeracy','Apply mathematical and statistical reasoning to computing problems.',6);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (5,'PLO8','Leadership','Demonstrate leadership, autonomy and responsibility in projects.',7);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (5,'PLO9','Personal','Engage in lifelong learning and professional development.',8);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (5,'PLO10','Entrepreneurial','Identify opportunities and apply entrepreneurial thinking to technology solutions.',9);
INSERT INTO plos (programme_id,code,domain,description,sort_order) VALUES (5,'PLO11','Ethics','Practise professional, ethical, legal and security-aware conduct in computing.',10);
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (1,'Programming Fundamentals',1,'["Write structured programs using variables, control flow and functions", "Debug and test small programs"]','["PLO1", "PLO3"]','["Python", "Problem Solving", "Debugging"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (1,'Computer Organisation and Architecture',1,'["Explain CPU, memory and I/O organisation"]','["PLO1"]','["Computer Architecture"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (1,'Discrete Mathematics',1,'["Apply logic, sets and graph theory to computing"]','["PLO7", "PLO2"]','["Discrete Math", "Logical Reasoning"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (1,'Database Systems',1,'["Design normalised relational schemas", "Write SQL queries and transactions"]','["PLO2", "PLO3"]','["SQL", "Database Design", "MySQL"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (1,'Object-Oriented Programming',1,'["Build applications using classes, inheritance and interfaces"]','["PLO3", "PLO1"]','["Java", "OOP"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (1,'Operating Systems',2,'["Explain processes, scheduling, memory and file systems", "Use Linux command line"]','["PLO1", "PLO3"]','["Linux", "Bash", "Operating Systems"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (1,'Data Communication and Networking',2,'["Configure IP addressing, routing and common protocols"]','["PLO1", "PLO3"]','["TCP/IP", "Networking", "Subnetting"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (1,'Web Application Development',2,'["Develop responsive web front-ends and REST back-ends"]','["PLO3", "PLO6"]','["HTML/CSS", "JavaScript", "REST APIs"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (1,'Cloud Computing Fundamentals',2,'["Describe IaaS, PaaS, SaaS and deployment models", "Provision virtual machines and storage in a public cloud"]','["PLO1", "PLO3", "PLO6"]','["Cloud Computing", "Huawei Cloud ECS", "Virtualisation"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (1,'Virtualisation and Containerisation',2,'["Build and run containers", "Orchestrate services with Kubernetes"]','["PLO3"]','["Docker", "Kubernetes"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (1,'Cloud Security',3,'["Apply identity, access and encryption controls in the cloud", "Assess cloud risks against compliance requirements"]','["PLO11", "PLO2"]','["Cloud Security", "IAM", "PDPA Compliance"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (1,'DevOps and Automation',3,'["Automate build, test and deploy with CI/CD pipelines", "Manage infrastructure as code"]','["PLO3", "PLO6"]','["CI/CD", "GitHub Actions", "Terraform"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (1,'Big Data and Analytics',3,'["Process large datasets and build dashboards"]','["PLO6", "PLO7"]','["Data Analytics", "SQL", "Data Visualisation"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (1,'Serverless and Cloud-Native Applications',3,'["Design event-driven serverless systems", "Deploy edge functions and managed databases"]','["PLO2", "PLO3"]','["Serverless", "Cloudflare Workers", "API Design"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (1,'Software Project Management',3,'["Plan and track projects with agile methods"]','["PLO4", "PLO8"]','["Agile/Scrum", "Project Management", "Teamwork"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (1,'Technopreneurship',3,'["Develop a business model for a technology product"]','["PLO10", "PLO5"]','["Entrepreneurship", "Pitching"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (1,'Industrial Training',4,'["Apply computing skills in an industry setting", "Report and present work professionally"]','["PLO4", "PLO5", "PLO9"]','["Professional Communication", "Teamwork"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (1,'Final Year Project',4,'["Plan, build and evaluate a substantial computing solution", "Present and defend the project"]','["PLO2", "PLO5", "PLO8", "PLO9"]','["Research", "Technical Writing", "Presentation"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (2,'Programming Fundamentals',1,'["Write structured programs"]','["PLO1", "PLO3"]','["Python", "Problem Solving"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (2,'Data Structures and Algorithms',1,'["Implement and analyse lists, trees, graphs and sorting"]','["PLO2", "PLO7"]','["Algorithms", "Data Structures"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (2,'Database Systems',1,'["Design schemas and write SQL"]','["PLO2", "PLO3"]','["SQL", "Database Design"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (2,'Object-Oriented Programming',1,'["Apply OOP design"]','["PLO3"]','["Java", "OOP"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (2,'Software Requirements Engineering',2,'["Elicit and specify requirements with UML"]','["PLO2", "PLO5"]','["Requirements Analysis", "UML"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (2,'Web Application Development',2,'["Build full-stack web apps"]','["PLO3"]','["JavaScript", "React", "Node.js"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (2,'Mobile Application Development',2,'["Build cross-platform mobile apps"]','["PLO3"]','["Flutter", "Mobile Development"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (2,'Software Testing',3,'["Design unit, integration and system tests"]','["PLO2", "PLO3"]','["Software Testing", "Jest"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (2,'Software Architecture',3,'["Choose architectural styles and design patterns"]','["PLO2"]','["Design Patterns", "System Design"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (2,'Human-Computer Interaction',3,'["Design and evaluate usable interfaces"]','["PLO2", "PLO5"]','["UI/UX Design", "Figma"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (2,'Software Project Management',3,'["Run agile projects"]','["PLO4", "PLO8"]','["Agile/Scrum", "Git"]');
INSERT INTO subjects (programme_id,name,year,clos,plo_codes,skills) VALUES (2,'Final Year Project',4,'["Deliver and defend a substantial project"]','["PLO2", "PLO5", "PLO8", "PLO9"]','["Research", "Technical Writing"]');
